% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  letterpaper,
  DIV=11,
  numbers=noendperiod]{scrartcl}

\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else  
    % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother

\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{241,243,245}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.40,0.45,0.13}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\BuiltInTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\ExtensionTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.28,0.35,0.67}{#1}}
\newcommand{\ImportTok}[1]{\textcolor[rgb]{0.00,0.46,0.62}{#1}}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.07,0.07,0.07}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother

\KOMAoption{captions}{tableheading}
\makeatletter
\@ifpackageloaded{tcolorbox}{}{\usepackage[skins,breakable]{tcolorbox}}
\@ifpackageloaded{fontawesome5}{}{\usepackage{fontawesome5}}
\definecolor{quarto-callout-color}{HTML}{909090}
\definecolor{quarto-callout-note-color}{HTML}{0758E5}
\definecolor{quarto-callout-important-color}{HTML}{CC1914}
\definecolor{quarto-callout-warning-color}{HTML}{EB9113}
\definecolor{quarto-callout-tip-color}{HTML}{00A047}
\definecolor{quarto-callout-caution-color}{HTML}{FC5300}
\definecolor{quarto-callout-color-frame}{HTML}{acacac}
\definecolor{quarto-callout-note-color-frame}{HTML}{4582ec}
\definecolor{quarto-callout-important-color-frame}{HTML}{d9534f}
\definecolor{quarto-callout-warning-color-frame}{HTML}{f0ad4e}
\definecolor{quarto-callout-tip-color-frame}{HTML}{02b875}
\definecolor{quarto-callout-caution-color-frame}{HTML}{fd7e14}
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother

\usepackage{bookmark}

\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Ultimate Athlete},
  pdfauthor={Dr William Kay},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}


\title{Ultimate Athlete}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Analysing peformance as a function of genotype}
\author{Dr William Kay}
\date{2025-10-02}

\begin{document}
\maketitle


\section{Tutorial}\label{tutorial}

\subsection{Introduction:}\label{introduction}

We want to analyse if there is an association between performance and
genotype.

In this tutorial we will use data collected in a previous year to
demonstrate this.

Specifically, we will be analysing if \textbf{VO}\(_2\) \textbf{max} is
associated with \textbf{ACE} genotype (II, ID, DD)

\subsection{Import the data into R}\label{import-the-data-into-r}

The data that you need is saved on Learning Central. The file is called
``\textbf{data.csv}''.

Start by downloading this file on to your device.

Then, open RStudio on your device and create a new R Script.

You can then copy the following code into your script and run it to
import the data.

\textbf{Note:} A new window should pop up on your device to allow you to
select the data file.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\FunctionTok{file.choose}\NormalTok{(), }\AttributeTok{header =}\NormalTok{ T, }\AttributeTok{stringsAsFactors =}\NormalTok{ T, }\AttributeTok{na.strings =} \StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\subsection{Explore the data}\label{explore-the-data}

Next, run a few basic functions to begin to explore the data.

For example:

\subsubsection{Structure}\label{structure}

Using the structure function \texttt{str()} shows you what variables you
have in the dataset, and what types of variables these are:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{str}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
'data.frame':   75 obs. of  16 variables:
 $ ID       : int  1 2 3 4 5 6 7 8 9 10 ...
 $ gender   : Factor w/ 2 levels "female","male": 1 1 2 2 1 2 2 1 2 2 ...
 $ weight   : num  44 66 91.5 82.1 63.5 ...
 $ height   : num  153 170 193 186 170 ...
 $ sys      : num  110 137 157 127 117 ...
 $ pp       : num  36.5 34 78.5 43 42 ...
 $ hr       : num  88 99 71.2 61 66.5 ...
 $ bmr      : num  18.7 22.4 24.4 24 22 23 21.3 27.7 22.3 28.1 ...
 $ ace      : Factor w/ 3 levels "DD","ID","II": 3 1 1 3 1 1 1 NA 1 2 ...
 $ actn3    : Factor w/ 3 levels "RR","RX","XX": 3 1 3 2 3 2 1 3 2 2 ...
 $ power    : int  277 426 1320 1102 675 1088 865 631 921 1013 ...
 $ pwrWeight: num  NA 6.5 14.4 13.4 10.6 15.2 12.5 8.4 12.8 10.9 ...
 $ vo2max   : num  NA 2 3.4 3.2 2.7 3.1 2.9 2.6 3.3 3.41 ...
 $ vo2maxb  : num  35.1 30 37.5 39.2 42.2 44.1 41.9 34 45.2 36.7 ...
 $ step     : int  7733 9280 12500 8502 11500 13043 7129 13533 NA 12000 ...
 $ exercise : Factor w/ 4 levels "active","light",..: 3 2 1 1 1 4 3 4 NA 3 ...
\end{verbatim}

\subsubsection{Summary function}\label{summary-function}

The \texttt{summary()} function applied to the dataset gives you a
summary of all variables:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
       ID          gender       weight           height           sys       
 Min.   : 1.0   female:42   Min.   : 42.00   Min.   :147.0   Min.   : 92.0  
 1st Qu.:19.5   male  :33   1st Qu.: 60.00   1st Qu.:165.0   1st Qu.:111.0  
 Median :38.0               Median : 70.00   Median :173.0   Median :122.5  
 Mean   :38.0               Mean   : 71.44   Mean   :173.1   Mean   :121.2  
 3rd Qu.:56.5               3rd Qu.: 79.75   3rd Qu.:179.8   3rd Qu.:130.0  
 Max.   :75.0               Max.   :105.00   Max.   :202.0   Max.   :156.8  
                                                                            
       pp               hr              bmr          ace      actn3   
 Min.   : 28.00   Min.   : 45.00   Min.   :16.10   DD  :26   RR  :20  
 1st Qu.: 37.00   1st Qu.: 67.25   1st Qu.:21.35   ID  :36   RX  :35  
 Median : 45.00   Median : 72.00   Median :22.80   II  :11   XX  :19  
 Mean   : 46.81   Mean   : 73.60   Mean   :23.38   NA's: 2   NA's: 1  
 3rd Qu.: 51.50   3rd Qu.: 79.00   3rd Qu.:24.75                      
 Max.   :106.00   Max.   :102.00   Max.   :35.10                      
                                                                      
     power          pwrWeight          vo2max         vo2maxb     
 Min.   : 277.0   Min.   : 5.500   Min.   :1.100   Min.   :18.90  
 1st Qu.: 519.5   1st Qu.: 8.625   1st Qu.:2.100   1st Qu.:33.05  
 Median : 655.0   Median : 9.850   Median :2.500   Median :37.30  
 Mean   : 746.2   Mean   :10.265   Mean   :2.685   Mean   :37.19  
 3rd Qu.: 954.5   3rd Qu.:12.200   3rd Qu.:3.200   3rd Qu.:41.35  
 Max.   :1711.0   Max.   :16.500   Max.   :4.900   Max.   :53.50  
                  NA's   :1        NA's   :1                      
      step              exercise 
 Min.   : 5000   active     : 4  
 1st Qu.: 8500   light      : 8  
 Median :10000   moderate   :36  
 Mean   :10101   very active:23  
 3rd Qu.:11180   NA's       : 4  
 Max.   :20000                   
 NA's   :5                       
\end{verbatim}

Remember you can apply functions to a specific variable by typing the
name of the dataset, followed by a dollar symbol \texttt{\$} and then
the name of the variable.

For example:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{vo2max)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  1.100   2.100   2.500   2.685   3.200   4.900       1 
\end{verbatim}

\subsubsection{mean}\label{mean}

You can calculate the mean value of a variable using \texttt{mean()}.

This is an example of performing \emph{descriptive statistics}:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{vo2max, }\AttributeTok{na.rm =}\NormalTok{ T)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 2.685
\end{verbatim}

Note that the \texttt{na.rm\ =\ T} part of this block of code above
tells R to remove (rm) any missing observations (na) before calculating
the mean.

\subsection{Visualise the data}\label{visualise-the-data}

It is always important to explore your data thoroughly. This includes
plotting your data, which helps to identify if there are any patterns or
outliers (extreme observations).

\subsubsection{Histogram}\label{histogram}

Let's start with a histogram to see what the distribution of VO\(_2\)
max looks like:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{hist}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{vo2max, }\AttributeTok{xlab =} \FunctionTok{expression}\NormalTok{(VO[}\DecValTok{2}\NormalTok{]}\SpecialCharTok{\textasciitilde{}}\StringTok{"max (L/min)"}\NormalTok{), }\AttributeTok{main =} \StringTok{""}\NormalTok{, }\AttributeTok{las =} \DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{ultimateAthlete_files/figure-pdf/unnamed-chunk-6-1.pdf}}

Note that this plot shows us all of the data, regardless of which
genotype it comes from.

\subsubsection{Boxplot}\label{boxplot}

If we wanted to, we could have a look at the same data using a boxplot:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{boxplot}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{vo2max, }\AttributeTok{las =} \DecValTok{1}\NormalTok{, }\AttributeTok{ylab =} \FunctionTok{expression}\NormalTok{(VO[}\DecValTok{2}\NormalTok{]}\SpecialCharTok{\textasciitilde{}}\StringTok{"max (L/min)"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{ultimateAthlete_files/figure-pdf/unnamed-chunk-7-1.pdf}}

Remember that the black horizontal line across the box shows the median
value of VO\(_2\) max. We could check this value by simply running:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{median}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{vo2max, }\AttributeTok{na.rm =}\NormalTok{ T)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 2.5
\end{verbatim}

\subsubsection{\texorpdfstring{Boxplot of VO\(_2\) max \textasciitilde{}
ACE}{Boxplot of VO\_2 max \textasciitilde{} ACE}}\label{boxplot-of-vo_2-max-ace}

What we really want is to see whether VO\(_2\) max varies according to
the ACE genotype. We can use \texttt{boxplot()} again for this:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{boxplot}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{vo2max }\SpecialCharTok{\textasciitilde{}}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{ace, }
        \AttributeTok{las =} \DecValTok{1}\NormalTok{, }
        \AttributeTok{ylab =} \FunctionTok{expression}\NormalTok{(VO[}\DecValTok{2}\NormalTok{]}\SpecialCharTok{\textasciitilde{}}\StringTok{"max (L/min)"}\NormalTok{), }
        \AttributeTok{xlab =} \StringTok{"Genotype"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{ultimateAthlete_files/figure-pdf/unnamed-chunk-9-1.pdf}}

So, based on this visual inspection alone, it looks like people with the
DD genotype might have a slightly higher average VO\(_2\) max than those
with ID or II.

We would need to perform a statistical test to determine whether our
data (our evidence!) is compelling enough to lead us to believe that
this is indeed the case. If not, then we would conclude that any
differences are down to chance (i.e., random variation).

\subsection{Perform a statistical
test}\label{perform-a-statistical-test}

If we just wanted to compare two groups, you will hopefully remember
from your Year 1 training in Biostatistics that we could consider using
a t-test.

For example, we may just want to compare people with the \textbf{DD}
genotype to those with \textbf{ID}.

Before we can perform the statistical test, there are a few things we
need to do.

\subsubsection{Create subsets for DD and
ID:}\label{create-subsets-for-dd-and-id}

First, it will make things easier if we create two subsets of the data:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{DD }\OtherTok{\textless{}{-}} \FunctionTok{subset}\NormalTok{(data, ace }\SpecialCharTok{==} \StringTok{"DD"}\NormalTok{)}
\NormalTok{ID }\OtherTok{\textless{}{-}} \FunctionTok{subset}\NormalTok{(data, ace }\SpecialCharTok{==} \StringTok{"ID"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\subsubsection{\texorpdfstring{Check the \emph{assumptions} of a
t-test}{Check the assumptions of a t-test}}\label{check-the-assumptions-of-a-t-test}

Next, you may remember that all statistical tests have what's called
``assumptions''.

These are the assumptions of a t-test:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Data are continuous (interval or ratio scale)
\item
  Data in each group are independent
\item
  Data in each group are approximately normally distributed
\item
  Variances are equal between groups (for a standard two-sample t-test)
\end{enumerate}

Let's check each in turn.

\textbf{First}, we know that the data are continuous. VO\(_2\) max is a
\textbf{continuous} variable.

\textbf{Second}, we know that the data in each group are
\textbf{independent}, because people can't have both DD \emph{and} ID
genotypes. They have to be one or the other. Hence the data in each
group are not paired in any way and do not \emph{depend} on one another.

\textbf{Third}, we should check if our data are \emph{approximately}
\textbf{normally distributed}. The VO\(_2\) max values in each genotype
group should roughly follow a bell-shaped curve. I always think it's
best to do this visually using a Q-Q plot:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{qqnorm}\NormalTok{(DD}\SpecialCharTok{$}\NormalTok{vo2max, }\AttributeTok{main =} \StringTok{"DD genotype"}\NormalTok{);}\FunctionTok{qqline}\NormalTok{(DD}\SpecialCharTok{$}\NormalTok{vo2max)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{ultimateAthlete_files/figure-pdf/unnamed-chunk-11-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{qqnorm}\NormalTok{(ID}\SpecialCharTok{$}\NormalTok{vo2max, }\AttributeTok{main =} \StringTok{"ID genotype"}\NormalTok{);}\FunctionTok{qqline}\NormalTok{(ID}\SpecialCharTok{$}\NormalTok{vo2max)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{ultimateAthlete_files/figure-pdf/unnamed-chunk-11-2.pdf}}

Remember, we are looking to see if the observations (dots) lie roughly
along the diagonal line. A little wiggle is fine, but we don't want
large deviations or unusual patterns.

In this case, both look fine!

And finally, \textbf{fourth}, we should check that our groups have equal
variance. Again, this can be done visually, using a boxplot:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{boxplot}\NormalTok{(DD}\SpecialCharTok{$}\NormalTok{vo2max, ID}\SpecialCharTok{$}\NormalTok{vo2max, }\AttributeTok{las =} \DecValTok{1}\NormalTok{, }\AttributeTok{names =} \FunctionTok{c}\NormalTok{(}\StringTok{"DD"}\NormalTok{, }\StringTok{"ID"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{ultimateAthlete_files/figure-pdf/unnamed-chunk-12-1.pdf}}

What we are looking for is that the \emph{spread} of the boxes and the
whiskers are roughly similar in both groups. In this case, they appear
to have about the same variability.

So, it looks like all four assumptions have been met, hence we can now
do the t-test:

\subsubsection{Perform a t-test}\label{perform-a-t-test}

The code to do this is very simple:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{t.test}\NormalTok{(DD}\SpecialCharTok{$}\NormalTok{vo2max, ID}\SpecialCharTok{$}\NormalTok{vo2max, }\AttributeTok{var.equal =}\NormalTok{ T)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

    Two Sample t-test

data:  DD$vo2max and ID$vo2max
t = 1.4884, df = 60, p-value = 0.1419
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -0.1037565  0.7071326
sample estimates:
mean of x mean of y 
 2.878077  2.576389 
\end{verbatim}

\subsection{Interpreting the output}\label{interpreting-the-output}

Let's go through it step by step:

\begin{itemize}
\item
  \texttt{Two\ Sample\ t-test}: this reminds you which test was
  performed.
\item
  \texttt{data}: this tells you what data were used in the test, in this
  case the VO\(_2\) max values from DD and ID.
\item
  \texttt{t\ =\ 1.4884}: This is the \textbf{test statistic}, indicating
  how extreme the difference is. You don't need to interpret the number
  itself, but you do need to report it.
\item
  \texttt{df\ =\ 60}: This is the \textbf{degrees of freedom} (total
  sample size minus the number of groups: 62 − 2).
\item
  \texttt{p-value\ =\ 0.1419}: This is the \textbf{probability} of
  observing a difference at least this large by chance. Here, it's
  \textasciitilde14\%, so it's \emph{not} statistically significant at
  the 0.05 threshold.
\item
  \texttt{alternative\ hypothesis}: Remember that tests have both a null
  and an alternative hypothesis. In this case the null hypothesis is
  that there is no difference in the means between DD and ID; in other
  words, the difference in means is equal to zero. The alternative
  hypothesis is that the difference in the means is \emph{not} equal to
  zero.
\item
  \texttt{sample\ estimates}: This tells you the mean VO\(_2\) max for
  each group (DD = 2.88, ID = 2.58 L/min).
\end{itemize}

We can check the \texttt{sample\ estimates} are correct by calculating
the means ourselves:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(DD}\SpecialCharTok{$}\NormalTok{vo2max, }\AttributeTok{na.rm =}\NormalTok{ T)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 2.878077
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(ID}\SpecialCharTok{$}\NormalTok{vo2max, }\AttributeTok{na.rm =}\NormalTok{ T)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 2.576389
\end{verbatim}

The difference in the means between the two groups is therefore:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(DD}\SpecialCharTok{$}\NormalTok{vo2max, }\AttributeTok{na.rm =}\NormalTok{ T) }\SpecialCharTok{{-}} \FunctionTok{mean}\NormalTok{(ID}\SpecialCharTok{$}\NormalTok{vo2max, }\AttributeTok{na.rm =}\NormalTok{ T)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 0.301688
\end{verbatim}

Now that we know this value we can better interpret the
\texttt{95\ percent\ confidence\ interval} bit of the output.

\begin{itemize}
\tightlist
\item
  \texttt{95\ percent\ confidence\ interval}: Range of plausible values
  for the difference in means if the experiment were repeated. In this
  case, the difference in the mean could be between \texttt{-0.1037565}
  and \texttt{0.7071326}
\end{itemize}

\subsection{Reporting the result}\label{reporting-the-result}

Now that we understand everything that the output is telling us, we can
report the result.

Remember to write about the biology first, and include the statistical
evidence.

Here's an example:

``People with the DD genotype had a mean VO\(_2\) max of 2.88 L/min,
whereas for people with the ID genotype this was 2.58 L/min, equating to
a difference of 0.30 L/min (95\% CI: -0.10 to 0.71; t = 1.49, df = 60, p
= 0.14). This difference was not statistically significant at the 0.05
level.''

\section{Exercises}\label{exercises}

\begin{tcolorbox}[enhanced jigsaw, breakable, opacityback=0, bottomrule=.15mm, bottomtitle=1mm, left=2mm, colback=white, opacitybacktitle=0.6, rightrule=.15mm, title=\textcolor{quarto-callout-note-color}{\faInfo}\hspace{0.5em}{Exercise 1}, leftrule=.75mm, toptitle=1mm, toprule=.15mm, colbacktitle=quarto-callout-note-color!10!white, coltitle=black, titlerule=0mm, arc=.35mm, colframe=quarto-callout-note-color-frame]

Look back through the tutorial and adapt the code I've given you to:

\begin{itemize}
\item
  Perform a t-test to compare DD versus II
\item
  Perform a t-test to compare ID versus II
\end{itemize}

\textbf{HINT:} Remember to create a subset for II and to check the
assumptions of a t-test before performing it!

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, breakable, opacityback=0, bottomrule=.15mm, bottomtitle=1mm, left=2mm, colback=white, opacitybacktitle=0.6, rightrule=.15mm, title=\textcolor{quarto-callout-note-color}{\faInfo}\hspace{0.5em}{Exercise 2}, leftrule=.75mm, toptitle=1mm, toprule=.15mm, colbacktitle=quarto-callout-note-color!10!white, coltitle=black, titlerule=0mm, arc=.35mm, colframe=quarto-callout-note-color-frame]

Now have a go at:

\begin{itemize}
\tightlist
\item
  Investigating whether power is associated with the ACTN-3 genotype
  (RR, RX, and XX).
\end{itemize}

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, breakable, opacityback=0, bottomrule=.15mm, bottomtitle=1mm, left=2mm, colback=white, opacitybacktitle=0.6, rightrule=.15mm, title=\textcolor{quarto-callout-note-color}{\faInfo}\hspace{0.5em}{Exercise 3}, leftrule=.75mm, toptitle=1mm, toprule=.15mm, colbacktitle=quarto-callout-note-color!10!white, coltitle=black, titlerule=0mm, arc=.35mm, colframe=quarto-callout-note-color-frame]

Now choose any other performance variable you want and explore whether
that varies in association with gender.

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, breakable, opacityback=0, bottomrule=.15mm, bottomtitle=1mm, left=2mm, colback=white, opacitybacktitle=0.6, rightrule=.15mm, title=\textcolor{quarto-callout-note-color}{\faInfo}\hspace{0.5em}{Exercise 4}, leftrule=.75mm, toptitle=1mm, toprule=.15mm, colbacktitle=quarto-callout-note-color!10!white, coltitle=black, titlerule=0mm, arc=.35mm, colframe=quarto-callout-note-color-frame]

Finally, see if you can import \emph{your own} data and do some of your
own analysis.

\end{tcolorbox}




\end{document}
